<?php
echo "<?php\n"; 
echo "// Query params are: utm_term={keyword}&utm_creative={creative}&utm_campaign={campaignid}&utm_position={adposition}&utm_network={network}&utm_target={target}&utm_placement={placement}&utm_match={matchtype} \n"; 
echo "\n"; 
echo "require_once dirname(__FILE__) . '/kclient.php';\n"; 
echo "$client = new KClient('http://87.249.53.59/api.php?', 'zqm75cmbzs8xxbs2kf5yvr8mcd1dkhyw');\n"; 
echo "$client->sendAllParams();       // to send all params from page query\n"; 
echo "$client->forceRedirectOffer();       // redirect to offer if an offer is chosen\n"; 
echo "// $client->param('sub_id_5', '123'); // you can send any params\n"; 
echo "// $client->keyword('PASTE_KEYWORD');  // send custom keyword\n"; 
echo "// $client->currentPageAsReferrer(); // to send current page URL as click referrer\n"; 
echo "// $client->disableSessions(); // to disable using session cookie (without this cookie restoreFromSession wouldn't work)\n"; 
echo "// $client->debug();              // to enable debug mode and show the errors\n"; 
echo "// $client->execute();             // request to api, show the output and continue\n"; 
echo "$client->executeAndBreak();     // to stop page execution if there is redirect or some output\n"; 
echo "?>\n"; 
echo "<!DOCTYPE html>\n"; 
echo "<!--\n"; 
echo "**********************************************************************************************************\n"; 
echo "    Copyright (c) \n"; 
echo "********************************************************************************************************** -->\n"; 
echo "\n"; 
echo "<!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\n"; 
echo "<!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\n"; 
echo "<!--[if !IE]><!-->\n"; 
echo "<html lang=\"en\">\n"; 
echo "<!--<![endif]-->\n"; 
echo "\n"; 
echo "<head>\n"; 
echo "    <title>App Landing - Html Template</title>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n"; 
echo "    <meta name=\"description\" content=\"\">\n"; 
echo "    <meta name=\"keywords\" content=\"\">\n"; 
echo "    <meta name=\"author\" content=\"Hsoft\">\n"; 
echo "    <meta name=\"MobileOptimized\" content=\"320\">\n"; 
echo "    <!-- favicon links-->\n"; 
echo "    <link rel=\"icon\" type=\"image/icon\" href=\"favicon.png\">\n"; 
echo "    <!-- main css -->\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/fonts.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/font-awesome.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/custom-animation.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/animate.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"js/plugins/swiper.min.css\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"css/style.css\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "    <!--Banner Section Start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='0'>\n"; 
echo "        <div class=\"ap_banner_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"ap_menu_wrap\">\n"; 
echo "                        <div class=\"col-lg-2 col-md-2 col-sm-2\">\n"; 
echo "                            <div class=\"ap_logo\">\n"; 
echo "                                <a href=\"#\"><img src=\"images/logo.png\" alt=\"\" class=\"img-responsive\"></a>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"col-lg-10 col-md-10 col-sm-10\">\n"; 
echo "                            <div class=\"ap_menus_wrapper\">\n"; 
echo "                                <button class=\"ap_menu_btn\">\n"; 
echo "								<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\n"; 
echo "							</button>\n"; 
echo "                                <nav>\n"; 
echo "                                    <div class=\"ap_menu\">\n"; 
echo "                                        <span class=\"ap_menu_close\"><i class=\"fa fa-times\" aria-hidden=\"true\"></i></span>\n"; 
echo "                                        <ul>\n"; 
echo "                                            <li><a data-scroll-nav='0'>home</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='1'>about</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='2'>features</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='3'>screenshots</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='4'>pricing</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='5'>download</a></li>\n"; 
echo "                                            <li><a data-scroll-nav='6'>contact</a></li>\n"; 
echo "                                        </ul>\n"; 
echo "                                    </div>\n"; 
echo "                                </nav>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"ap_banner\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                            <div class=\"ap_device wow slideleft\">\n"; 
echo "                                <img src=\"http://via.placeholder.com/343x705\" alt=\"\" class=\"img-responsive\" />\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                        <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                            <div class=\"ap_banner_data\">\n"; 
echo "                                <h1>the best way to showcase your app</h1>\n"; 
echo "                                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.</p>\n"; 
echo "                                <div class=\"ap_banner_btn\">\n"; 
echo "                                    <a href=\"#\"><img src=\"images/App-store.jpg\" class=\"img-responsive\" alt=\"\"/></a>\n"; 
echo "                                    <a href=\"#\"><img src=\"images/Google-play.jpg\" class=\"img-responsive\" alt=\"\"/></a>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"count-particles\" id=\"particles-js\">\n"; 
echo "                <span class=\"js-count-particles\"></span>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--About Section Start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='1'>\n"; 
echo "        <div class=\"ap_about_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                        <div class=\"ap_heading\">\n"; 
echo "                            <h1>about <span class=\"ap_bold\">us</span></h1>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                        <div class=\"ap_about_img wow slideleft\">\n"; 
echo "                            <img src=\"http://via.placeholder.com/555x389\" alt=\"\" class=\"img-responsive\" />\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-6 col-md-6\">\n"; 
echo "                        <div class=\"ap_about_data wow slideright\">\n"; 
echo "                            <h2>who are appo</h2>\n"; 
echo "                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here.</p>\n"; 
echo "                            <p>Making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>\n"; 
echo "                            <a href=\"#\" class=\"ap_btn\">read more</a>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--Feature Section Start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='2'>\n"; 
echo "        <div class=\"ap_feature_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                        <div class=\"ap_heading\">\n"; 
echo "                            <h1>brilliant <span class=\"ap_bold\"> features</span></h1>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                        <div class=\"ap_feature_box\">\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"2s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2 col-lg-push-10 col-md-push-10\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-light-bulb flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10 col-lg-pull-2 col-md-pull-2\">\n"; 
echo "                                        <div class=\"ap_feature_text text-right\">\n"; 
echo "                                            <h2>Creative Design</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"4s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2 col-lg-push-10 col-md-push-10\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-notification flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10 col-lg-pull-2 col-md-pull-2\">\n"; 
echo "                                        <div class=\"ap_feature_text text-right\">\n"; 
echo "                                            <h2>Notification Viewing</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"6s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2 col-lg-push-10 col-md-push-10\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-key flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10 col-lg-pull-2 col-md-pull-2\">\n"; 
echo "                                        <div class=\"ap_feature_text text-right\">\n"; 
echo "                                            <h2>Extreme Security</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                        <div class=\"ap_feature_mob_img wow frombottom\">\n"; 
echo "                            <img src=\"http://via.placeholder.com/314x648\" alt=\"\" class=\"img-responsive\" />\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                        <div class=\"ap_feature_box\">\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"2s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-weather flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10\">\n"; 
echo "                                        <div class=\"ap_feature_text\">\n"; 
echo "                                            <h2>Color Schemes</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"4s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-edit flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10\">\n"; 
echo "                                        <div class=\"ap_feature_text\">\n"; 
echo "                                            <h2>Pixel Perfect Design</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"row\">\n"; 
echo "                                <div class=\"ap_feature_inner_box wow fadeIn\" data-wow-duration=\"6s\">\n"; 
echo "                                    <div class=\"col-lg-2 col-md-2\">\n"; 
echo "                                        <div class=\"ap_feature_img\">\n"; 
echo "                                            <i class=\"flaticon-bar-chart flaticon\"></i>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"col-lg-10 col-md-10\">\n"; 
echo "                                        <div class=\"ap_feature_text\">\n"; 
echo "                                            <h2>Great Performance</h2>\n"; 
echo "                                            <p>Many desktop publishing packs and web page editors now use Lorem Ipsum as default model</p>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--Screenshots Section Start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='3'>\n"; 
echo "        <div class=\"ap_screen_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                        <div class=\"ap_heading\">\n"; 
echo "                            <h1>awesome <span class=\"ap_bold\"> screenshots</span></h1>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-10 col-md-10 col-lg-offset-1 col-md-offset-1\">\n"; 
echo "                        <div class=\"ap_screen_slider wow fadeIn\">\n"; 
echo "                            <div class=\"swiper-container\">\n"; 
echo "                                <div class=\"swiper-wrapper\">\n"; 
echo "                                    <div class=\"swiper-slide\" style=\"background-image:url(http://via.placeholder.com/325x578)\"></div>\n"; 
echo "                                    <div class=\"swiper-slide\" style=\"background-image:url(http://via.placeholder.com/325x578)\"></div>\n"; 
echo "                                    <div class=\"swiper-slide\" style=\"background-image:url(http://via.placeholder.com/325x578)\"></div>\n"; 
echo "                                    <div class=\"swiper-slide\" style=\"background-image:url(http://via.placeholder.com/325x578)\"></div>\n"; 
echo "                                    <div class=\"swiper-slide\" style=\"background-image:url(http://via.placeholder.com/325x578)\"></div>\n"; 
echo "                                </div>\n"; 
echo "                                <!-- Add Pagination -->\n"; 
echo "                                <div class=\"swiper-pagination\"></div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"app-screen-mobile-image\"></div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--Pricing table section start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='4'>\n"; 
echo "        <div class=\"ap_pricing_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                        <div class=\"ap_heading\">\n"; 
echo "                            <h1>pricing <span class=\"ap_bold\"> table</span></h1>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-10 col-md-10 col-lg-offset-1 col-md-offset-1\">\n"; 
echo "                        <div class=\"row\">\n"; 
echo "                            <div class=\"ap_pricing_inner\">\n"; 
echo "                                <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                                    <div class=\"ap_price_box wow fadeIn\">\n"; 
echo "                                        <div class=\"ap_price_head\">\n"; 
echo "                                            <h2>standard</h2>\n"; 
echo "                                            <h1>$20</h1>\n"; 
echo "                                            <p>per month</p>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"ap_price_list\">\n"; 
echo "                                            <ul>\n"; 
echo "                                                <li>Free consultment</li>\n"; 
echo "                                                <li>Multiplatform</li>\n"; 
echo "                                                <li>Collaboration</li>\n"; 
echo "                                                <li>Daily support</li>\n"; 
echo "                                                <li>Updates</li>\n"; 
echo "                                            </ul>\n"; 
echo "                                            <a href=\"#\" class=\"ap_btn\">purchase now</a>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                                    <div class=\"ap_price_box ap_price_middle_box wow fadeIn\">\n"; 
echo "                                        <div class=\"ap_price_head\">\n"; 
echo "                                            <h2>business</h2>\n"; 
echo "                                            <h1>$20</h1>\n"; 
echo "                                            <p>per month</p>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"ap_price_list\">\n"; 
echo "                                            <ul>\n"; 
echo "                                                <li>Free consultment</li>\n"; 
echo "                                                <li>Multiplatform</li>\n"; 
echo "                                                <li>Collaboration</li>\n"; 
echo "                                                <li>Daily support</li>\n"; 
echo "                                                <li>Updates</li>\n"; 
echo "                                            </ul>\n"; 
echo "                                            <a href=\"#\" class=\"ap_btn\">purchase now</a>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                                    <div class=\"ap_price_box wow fadeIn\">\n"; 
echo "                                        <div class=\"ap_price_head\">\n"; 
echo "                                            <h2>professional</h2>\n"; 
echo "                                            <h1>$20</h1>\n"; 
echo "                                            <p>per month</p>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"ap_price_list\">\n"; 
echo "                                            <ul>\n"; 
echo "                                                <li>Free consultment</li>\n"; 
echo "                                                <li>Multiplatform</li>\n"; 
echo "                                                <li>Collaboration</li>\n"; 
echo "                                                <li>Daily support</li>\n"; 
echo "                                                <li>Updates</li>\n"; 
echo "                                            </ul>\n"; 
echo "                                            <a href=\"#\" class=\"ap_btn\">purchase now</a>\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--Now Available section start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='5'>\n"; 
echo "        <div class=\"ap_new_wrapper\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                        <div class=\"ap_heading\">\n"; 
echo "                            <h1>now <span class=\"ap_bold\"> available</span></h1>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"col-lg-8 col-md-8 col-lg-offset-2 col-md-offset-2\">\n"; 
echo "                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed eiusmod tempor incididunt ut labore et dolore magna aliqua enim.</p>\n"; 
echo "                        <div class=\"ap_banner_btn\">\n"; 
echo "                            <a href=\"#\"><img src=\"images/App-store1.png\" class=\"img-responsive\" alt=\"\"></a>\n"; 
echo "                            <a href=\"#\"><img src=\"images/App-store2.png\" class=\"img-responsive\" alt=\"\"></a>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--New Available section start-->\n"; 
echo "    <div class=\"ap_section\" data-scroll-index='6'>\n"; 
echo "        <div class=\"ap_map_wrapper\">\n"; 
echo "            <div class=\"container-fluid\">\n"; 
echo "                <div class=\"row\">\n"; 
echo "                    <div class=\"contact_map\">\n"; 
echo "                        <div id=\"contact_map\"></div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <!----contact form section---->\n"; 
echo "            <div class=\"ap_con_wrapper\">\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"ap_con_inner\">\n"; 
echo "                            <div class=\"col-lg-8 col-md-8\">\n"; 
echo "                                <div class=\"ap_con_form wow slideleft\">\n"; 
echo "                                    <h1>leave a comment</h1>\n"; 
echo "                                    <form id=\"contactForm\" data-toggle=\"validator\">\n"; 
echo "                                        <div class=\"form-group\">\n"; 
echo "                                            <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Name\" required>\n"; 
echo "											<div class=\"help-block with-errors\"></div>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"form-group\">\n"; 
echo "                                            <input type=\"text\" class=\"form-control\" id=\"email\" placeholder=\"Email\" required>\n"; 
echo "											<div class=\"help-block with-errors\"></div>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"form-group\">\n"; 
echo "                                            <textarea name=\"your-message\" cols=\"3\" rows=\"5\" class=\"form-control\" placeholder=\"Message\" id=\"message\"></textarea>\n"; 
echo "											<div class=\"help-block with-errors\"></div>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div class=\"form_btn\">\n"; 
echo "                                            <button type=\"submit\" id=\"form-submit\" class=\"ap_btn submit_button btn-success\">Submit</button>\n"; 
echo "                                        </div>\n"; 
echo "                                        <div id=\"msgSubmit\" class=\"h3 text-center hidden\"></div>\n"; 
echo "                                    </form>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"col-lg-4 col-md-4\">\n"; 
echo "                                <div class=\"ap_con_info wow slideright\">\n"; 
echo "                                    <h1>get in touch</h1>\n"; 
echo "                                    <div class=\"ap_con_list\">\n"; 
echo "                                        <span class=\"con_icon\">\n"; 
echo "								<i class=\"flaticon flaticon-location-pointer\"></i>	\n"; 
echo "							</span>\n"; 
echo "                                        <div class=\"con_data\">\n"; 
echo "                                            865 Florence Street Longview, TX 75601\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"ap_con_list\">\n"; 
echo "                                        <span class=\"con_icon\">\n"; 
echo "								<i class=\"flaticon flaticon-telephone\"></i>	\n"; 
echo "							</span>\n"; 
echo "                                        <div class=\"con_data\">\n"; 
echo "                                            (+1) 903-452-9930\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"ap_con_list\">\n"; 
echo "                                        <span class=\"con_icon\">\n"; 
echo "								<i class=\"flaticon flaticon-close-envelope\"></i>	\n"; 
echo "							</span>\n"; 
echo "                                        <div class=\"con_data\">\n"; 
echo "                                            support@templatebundle.net\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <div class=\"ap_con_list\">\n"; 
echo "                                        <span class=\"con_icon\">\n"; 
echo "								<i class=\"flaticon flaticon-clock\"></i>	\n"; 
echo "							</span>\n"; 
echo "                                        <div class=\"con_data\">\n"; 
echo "                                            Open Hours : 9:00 to 18:00 Mon-Sat\n"; 
echo "                                        </div>\n"; 
echo "                                    </div>\n"; 
echo "                                    <ul class=\"ap_footer_icon\">\n"; 
echo "                                        <li><a href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\n"; 
echo "                                        <li><a href=\"#\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\n"; 
echo "                                        <li><a href=\"#\"><i class=\"fa fa-pinterest-p\" aria-hidden=\"true\"></i></a></li>\n"; 
echo "                                        <li><a href=\"#\"><i class=\"fa fa-linkedin\" aria-hidden=\"true\"></i></a></li>\n"; 
echo "                                    </ul>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--bottom footer start-->\n"; 
echo "    <div class=\"ap_bottom_footer\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12 col-md-12\">\n"; 
echo "                    <p>Copyright &copy; 2017, All Rights Reserved.</p>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "    <!--js start-->\n"; 
echo "    <script src=\"js/jquery.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/popper.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/scrollIt.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/particles.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/app.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/validator.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/wow.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/plugins/swiper.min.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script src=\"js/custom.js\" type=\"text/javascript\"></script>\n"; 
echo "    <script>\n"; 
echo "        $(function() {\n"; 
echo "            $.scrollIt();\n"; 
echo "        });\n"; 
echo "    </script>\n"; 
echo "    <!--map-->\n"; 
echo "    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDNdePPJKYq0ptBV_AFi_4RnmUtMa1ZLFg&libraries=places\">\n"; 
echo "    </script>\n"; 
echo "    <script>\n"; 
echo "        $(document).ready(function() {\n"; 
echo "            var myCenter = new google.maps.LatLng(51.508530, -0.076132);\n"; 
echo "\n"; 
echo "            function initialize() {\n"; 
echo "                var mapProp = {\n"; 
echo "                    center: myCenter,\n"; 
echo "                    zoom: 8,\n"; 
echo "                    scrollwheel: false,\n"; 
echo "                    mapTypeId: google.maps.MapTypeId.ROADMAP\n"; 
echo "                };\n"; 
echo "                var map = new google.maps.Map(document.getElementById(\"contact_map\"), mapProp);\n"; 
echo "                var icon = {\n"; 
echo "                    url: 'images/map_pin.png'\n"; 
echo "                };\n"; 
echo "                var marker = new google.maps.Marker({\n"; 
echo "                    position: myCenter,\n"; 
echo "                    map: map,\n"; 
echo "                    title: 'Template Bundle',\n"; 
echo "                    icon: icon\n"; 
echo "                });\n"; 
echo "                marker.setMap(map);\n"; 
echo "                var infowindow = new google.maps.InfoWindow({\n"; 
echo "                    content: \"<span> Template Bundle </span>\"\n"; 
echo "                });\n"; 
echo "                google.maps.event.addListener(marker, 'click', function() {\n"; 
echo "                    infowindow.open(map, marker);\n"; 
echo "                });\n"; 
echo "            }\n"; 
echo "            google.maps.event.addDomListener(window, 'load', initialize);\n"; 
echo "        });\n"; 
echo "    </script>\n"; 
echo "\n"; 
echo "</body>\n";
?>
